/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.AppServices;
import ticket.booking.services.TrainService;
import ticket.booking.services.UserBookingService;

import java.io.IOException;
import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;

        try {
            userBookingService = new UserBookingService();
        } catch (IOException e) {
            System.out.println("There is something wrong" + e.getMessage());
            return;
        }

        // Pre-login menu
        while (option != 3) {
            System.out.println("\nWelcome to IRCTC!");
            System.out.println("Choose option:");
            System.out.println("1. sign up");
            System.out.println("2. login");
            System.out.println("3. Exit");

            if (!sc.hasNextInt()) {
                System.out.println("Invalid input! Please enter a number.");
                sc.next(); // flush bad input
                continue;
            }
            option = sc.nextInt();
            switch (option) {
                case 1:
                    AppServices.signUp(sc, userBookingService);
                    break;
                case 2:
                    User loggedInUser = AppServices.login(sc);
                    if (loggedInUser != null) {
                        try {
                            userBookingService = new UserBookingService(loggedInUser);
                            postLoginMenu(sc, userBookingService, loggedInUser);
                        } catch (IOException e) {
                            throw new RuntimeException(e);
                        }
                    }
                    break;
                case 3:
                    System.out.println("Goodbye!");
                    break;
                default:
                    System.out.println("Invalid option. Please choose 1-3.");
                    break;
            }
        }
    }


    //Post Login Menu
    private static void postLoginMenu(Scanner sc, UserBookingService userBookingService,User loggedInUser) throws IOException {
        Train trainSelectedForBooking = new Train();
        int option = 0;
        while (option != 5) {
            System.out.println("\nWhat would you like to do?");
            System.out.println("1. Fetch Bookings");
            System.out.println("2. Search train");
            System.out.println("3. Book a Seat");
            System.out.println("4. Cancel my Booking");
            System.out.println("5. Logout");

            if (!sc.hasNextInt()) {
                System.out.println("Invalid input! Please enter a number.");
                sc.next(); // flush bad input
                continue;
            }
            option = sc.nextInt();

            switch (option) {
                case 1:
                    System.out.println("Fetching Bookings....");
                    userBookingService.fetchBooking(loggedInUser);
                    break;
                case 2:
                    Train selected = AppServices.searchTrain(sc, userBookingService);
                    if (selected != null)
                        trainSelectedForBooking = selected;
                    break;
                case 3:
                    AppServices.bookSeat(sc, userBookingService, trainSelectedForBooking, loggedInUser);
                    break;
                case 4:
                    AppServices.cancelBooking(sc, userBookingService, loggedInUser);
                    break;
                case 5:
                    System.out.println("Logged out successfully!");
                    break;

                default:
                    System.out.println("Invalid option. Please choose 1-5.");
                    break;
            }
        }
    }
}

